### ISSUE TITLE
Same GUID as SDL2-CS

### ISSUE THREAD

**Issue by benklett** [dan200/MiniTK#1]
If you want to use this project in combination with SDL2-CS, you cannot do this because they have the same GUID.

The GUID is defined in the csproj:
```xml
<ProjectGuid>{85480198-8711-4355-830E-72FD794AD3F6}</ProjectGuid>
```

It should be possible to fix this by recreating the csproj file and add everything in again. It could also work if you replace all occurrences of the GUID with a new one, but I am not sure about this one.

**Comment by dan200** [comment]
Well spotted, will fix asap

**Comment by dan200** [comment]
Fixed.

**Comment by benklett** [comment]
Cool, thank you very much.
